name: Abyss
version: 1.0.0
description: Abyss Minecraft Plugin
author: Revo & Torress

main: com.rtp.Plugin

commands:
  AbyssOpen:
    description: "Abyss Opened"
    aliases: [ao]
    usage: "Abyss can not be opened"
  AbyssClose:
    description: "Abyss Closed"
    aliases: [ac]
    usage: "Abyss can not be closed"