name: Abyss
version: 1.0.0
description: Abyss Minecraft Plugin
author: Revo & Torress

main: com.rtp.Plugin

commands:
  abyss:
    description: Abyss main command
    usage: Type /abyss to open abyss!