main: commandExecutor.Main
name: AbyssPlugin
author: TorresS and Revo
version: 1.0

commands:
  AbyssOpen:
    description: "Abyss Opened"
    aliases: [ao]
    usage: "Abyss can not be opened"
  AbyssClose:
    description: "Abyss Closed"
    aliases: [ac]
    usage: "Abyss can not be closed"